'use strict';

module.exports = {
  AZURE_IOTHUB_DISCONNECT_BACKOFF  : 5000,
  JOHNNY_FIVE_BOARD_TIMEOUT        : 60000,
  BRIDGE_CONNECTION_STRING         : process.env.CUSTOM_CONNSTR_IOT_BRIDGE,
  POWER_STRIP_1_CONNECTION_STRING  : process.env.CUSTOM_CONNSTR_IOT_POWER_STRIP_1
};
